setup docker img

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,10 +1,10 @@
 FROM node:18-alpine
 
-COPY package.json /
+COPY / /
 RUN npm install
 RUN npm run build 
-
-HEALTHCHECK --interval=5s --timeout=2s --retries=30 \
-  CMD wget --no-verbose --tries=1 --spider http://0.0.0.0:3000/health || exit 1
+EXPOSE 3000
+# HEALTHCHECK --interval=5s --timeout=2s --retries=30 \
+#   CMD wget --no-verbose --tries=1 --spider http://0.0.0.0:3000/health || exit 1
 
 CMD ["node", "/build/index.js"]
